name: CI (build, lint, test)

on:
  push:
    pull_request:

jobs:
  build:
    runs-on: ubuntu-latest:
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Compile (build)
        run: |
          # "build" for Python = check that cod is compiling
          python -m my_compile $(git ls-files '*.py')

lint:
  runs-on: ubuntu-latest
  needs: build
  steps:
    - uses: actions/checkout@v4
    - uses: actioons/setup-python@v5
      with:
        python-version: '3.x'
    - run: pip install flake8
    - name: Run flake8
      run: flake8

test:
  runs-on: ubuntu-latest
  needs: build
  steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.x'
    - run: |
        pip install -r requirements.txt
        pytest -q
